/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secureaccess;

import java.awt.Color;

/**
 *
 * @author shaun
 */
public class loginGUI extends javax.swing.JFrame {

    /**
     * Creates new form loginGUI
     */
    public loginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        submitJbtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        signupJlbl = new javax.swing.JLabel();
        passwordJlbl = new javax.swing.JLabel();
        emailJlbl = new javax.swing.JLabel();
        emailJtf = new javax.swing.JTextField();
        accountJbtn = new javax.swing.JButton();
        passwordJpf = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        welcome2Jlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(227, 238, 212));

        jSeparator4.setBackground(new java.awt.Color(102, 66, 41));
        jSeparator4.setForeground(new java.awt.Color(102, 66, 41));

        submitJbtn.setBackground(new java.awt.Color(4, 50, 34));
        submitJbtn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        submitJbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitJbtn.setText("SUBMIT");

        jSeparator6.setBackground(new java.awt.Color(102, 66, 41));
        jSeparator6.setForeground(new java.awt.Color(102, 66, 41));

        signupJlbl.setBackground(new java.awt.Color(227, 238, 212));
        signupJlbl.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        signupJlbl.setForeground(new java.awt.Color(102, 66, 41));
        signupJlbl.setText("Log In");

        passwordJlbl.setBackground(new java.awt.Color(227, 238, 212));
        passwordJlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        passwordJlbl.setForeground(new java.awt.Color(102, 66, 41));
        passwordJlbl.setText("PASSWORD");

        emailJlbl.setBackground(new java.awt.Color(227, 238, 212));
        emailJlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        emailJlbl.setForeground(new java.awt.Color(102, 66, 41));
        emailJlbl.setText("EMAIL");

        emailJtf.setBackground(new java.awt.Color(227, 238, 212));
        emailJtf.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        emailJtf.setForeground(new java.awt.Color(102, 66, 41));
        emailJtf.setText("Enter your email");
        emailJtf.setBorder(null);
        emailJtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailJtfFocusGained(evt);
            }
        });
        emailJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJtfActionPerformed(evt);
            }
        });

        accountJbtn.setBackground(new java.awt.Color(227, 238, 212));
        accountJbtn.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        accountJbtn.setForeground(new java.awt.Color(102, 66, 41));
        accountJbtn.setText("Don't have an account?");
        accountJbtn.setBorder(null);
        accountJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountJbtnActionPerformed(evt);
            }
        });

        passwordJpf.setBackground(new java.awt.Color(227, 238, 212));
        passwordJpf.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        passwordJpf.setForeground(new java.awt.Color(102, 66, 41));
        passwordJpf.setText("Enter your password");
        passwordJpf.setBorder(null);
        passwordJpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordJpfFocusGained(evt);
            }
        });
        passwordJpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJpfActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(4, 50, 34));

        welcomeJlbl.setBackground(new java.awt.Color(4, 50, 34));
        welcomeJlbl.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeJlbl.setText("Welcome back to Secure Access");

        welcome2Jlbl.setBackground(new java.awt.Color(4, 50, 34));
        welcome2Jlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        welcome2Jlbl.setForeground(new java.awt.Color(255, 255, 255));
        welcome2Jlbl.setText("Please provide some information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcome2Jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeJlbl)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(welcomeJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcome2Jlbl)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(submitJbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accountJbtn))
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator6)
                            .addComponent(passwordJlbl)
                            .addComponent(emailJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailJtf)
                            .addComponent(passwordJpf, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(signupJlbl)))
                .addGap(0, 93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(signupJlbl)
                .addGap(35, 35, 35)
                .addComponent(emailJlbl)
                .addGap(18, 18, 18)
                .addComponent(emailJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(passwordJlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordJpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accountJbtn)
                        .addComponent(submitJbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailJtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailJtfFocusGained
        // TODO add your handling code here:
        if (emailJtf.getText().equals("Enter your email")) {
            emailJtf.setText("");
            emailJtf.setForeground(new Color(169, 113, 66));
        }
    }//GEN-LAST:event_emailJtfFocusGained

    private void emailJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJtfActionPerformed

    private void passwordJpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJpfFocusGained
        // TODO add your handling code here:
        if (passwordJpf.getText().equals("Enter your password")) {
            passwordJpf.setText("");
            passwordJpf.setForeground(new Color(169, 113, 66));
        }
    }//GEN-LAST:event_passwordJpfFocusGained

    private void passwordJpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJpfActionPerformed

    private void accountJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountJbtnActionPerformed
        // TODO add your handling code here:
        signupGUI myGUI = new signupGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountJbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountJbtn;
    private javax.swing.JLabel emailJlbl;
    private javax.swing.JTextField emailJtf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel passwordJlbl;
    private javax.swing.JPasswordField passwordJpf;
    private javax.swing.JLabel signupJlbl;
    private javax.swing.JButton submitJbtn;
    private javax.swing.JLabel welcome2Jlbl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
